services:
  prediction_service:
    build:
      context: ./prediction_service
      dockerfile: Dockerfile
    container_name: prediction_service_container
    working_dir: /app
    volumes:
      - ./prediction_service:/app
    ports:
      - 8080:8080
    command: python detect_fake.py
